"""Stable validation finding codes.

Codes are part of the contract: tests and the negative-fixture manifest match on them.
Rename only with an ADR-003 update. Prefixes name the layer that produced the finding:

- ``REGISTRY_*`` schema registry / dispatch
- ``SCHEMA_*``   JSON Schema (structure)
- ``SEM_*``      single-artifact semantic rules (Python)
- ``CHAIN_*``    cross-artifact evidence-chain rules (Python)
"""

from __future__ import annotations

from dataclasses import dataclass

# Registry / dispatch
REGISTRY_UNKNOWN_ARTIFACT_TYPE = "REGISTRY_UNKNOWN_ARTIFACT_TYPE"
REGISTRY_NOT_AN_OBJECT = "REGISTRY_NOT_AN_OBJECT"

# Schema
SCHEMA_INVALID = "SCHEMA_INVALID"

# Single-artifact semantic
SEM_DUPLICATE_ID = "SEM_DUPLICATE_ID"
SEM_UNRESOLVED_SOURCE = "SEM_UNRESOLVED_SOURCE"
SEM_UNRESOLVED_CLAIM = "SEM_UNRESOLVED_CLAIM"
SEM_UNSUPPORTED_INFERENCE = "SEM_UNSUPPORTED_INFERENCE"
SEM_CONTACT_POLICY_VERSION_MISMATCH = "SEM_CONTACT_POLICY_VERSION_MISMATCH"
SEM_CONTACT_READINESS_OVERSTATED = "SEM_CONTACT_READINESS_OVERSTATED"
SEM_CONTACT_OUTCOME_OVERSTATED = "SEM_CONTACT_OUTCOME_OVERSTATED"
SEM_UNRESOLVED_CONTACT = "SEM_UNRESOLVED_CONTACT"
SEM_COMMERCIAL_VIABLE_WITHOUT_POLICY = "SEM_COMMERCIAL_VIABLE_WITHOUT_POLICY"
SEM_DRAFT_HASH_MISMATCH = "SEM_DRAFT_HASH_MISMATCH"
SEM_QA_HARD_FAIL_COMPENSATED = "SEM_QA_HARD_FAIL_COMPENSATED"
SEM_EVAL_PASS_WITHOUT_EXECUTION = "SEM_EVAL_PASS_WITHOUT_EXECUTION"
SEM_SKILL_SEND_AUTHORITY = "SEM_SKILL_SEND_AUTHORITY"
SEM_SEND_PERMISSION_INCONSISTENT = "SEM_SEND_PERMISSION_INCONSISTENT"
SEM_SEND_PERMISSION_EXPIRED = "SEM_SEND_PERMISSION_EXPIRED"
SEM_SEND_GATE_APPROVAL = "SEM_SEND_GATE_APPROVAL"
SEM_SEND_GATE_QA = "SEM_SEND_GATE_QA"
SEM_SEND_GATE_CONTACT = "SEM_SEND_GATE_CONTACT"
SEM_SEND_GATE_COMPLIANCE = "SEM_SEND_GATE_COMPLIANCE"
SEM_SEND_GATE_SUPPRESSION = "SEM_SEND_GATE_SUPPRESSION"
SEM_SEND_GATE_DUPLICATE = "SEM_SEND_GATE_DUPLICATE"
SEM_SEND_GATE_FRESHNESS = "SEM_SEND_GATE_FRESHNESS"
SEM_REPLY_FOLLOWUPS_NOT_STOPPED = "SEM_REPLY_FOLLOWUPS_NOT_STOPPED"
SEM_REPLY_CLASSIFIED_BEFORE_STOP = "SEM_REPLY_CLASSIFIED_BEFORE_STOP"

# Cross-artifact chain
CHAIN_DUPLICATE_ARTIFACT_ID = "CHAIN_DUPLICATE_ARTIFACT_ID"
CHAIN_DUPLICATE_CLAIM_ID = "CHAIN_DUPLICATE_CLAIM_ID"
CHAIN_DANGLING_REFERENCE = "CHAIN_DANGLING_REFERENCE"
CHAIN_CYCLE = "CHAIN_CYCLE"
CHAIN_ILLEGAL_INPUT_TYPE = "CHAIN_ILLEGAL_INPUT_TYPE"
CHAIN_MISSING_REQUIRED_INPUT = "CHAIN_MISSING_REQUIRED_INPUT"
CHAIN_AMBIGUOUS_INPUT = "CHAIN_AMBIGUOUS_INPUT"
CHAIN_UNRESOLVED_SOURCE = "CHAIN_UNRESOLVED_SOURCE"
CHAIN_UNRESOLVED_CLAIM = "CHAIN_UNRESOLVED_CLAIM"
CHAIN_UNRESOLVED_REFERENCE = "CHAIN_UNRESOLVED_REFERENCE"
CHAIN_UNKNOWN_AS_SUPPORT = "CHAIN_UNKNOWN_AS_SUPPORT"
CHAIN_HYPOTHESIS_NOT_BRAND_GROUNDED = "CHAIN_HYPOTHESIS_NOT_BRAND_GROUNDED"
CHAIN_ILLEGAL_EXTERNAL_FRAMING = "CHAIN_ILLEGAL_EXTERNAL_FRAMING"
CHAIN_UNRESOLVED_CONFLICT = "CHAIN_UNRESOLVED_CONFLICT"
CHAIN_AFTER_STOP_OUTCOME = "CHAIN_AFTER_STOP_OUTCOME"
CHAIN_CONTACT_NOT_READY = "CHAIN_CONTACT_NOT_READY"
CHAIN_CONTACT_MISMATCH = "CHAIN_CONTACT_MISMATCH"
CHAIN_CONTACT_NOT_ELIGIBLE = "CHAIN_CONTACT_NOT_ELIGIBLE"
CHAIN_DRAFT_HASH_MISMATCH = "CHAIN_DRAFT_HASH_MISMATCH"
CHAIN_APPROVAL_NOT_APPROVED = "CHAIN_APPROVAL_NOT_APPROVED"
CHAIN_QA_NOT_READY = "CHAIN_QA_NOT_READY"
CHAIN_GATE_MISMATCH = "CHAIN_GATE_MISMATCH"
CHAIN_BINDING_MISMATCH = "CHAIN_BINDING_MISMATCH"
CHAIN_SEND_WITHOUT_AUTHORIZATION = "CHAIN_SEND_WITHOUT_AUTHORIZATION"
CHAIN_SEND_OUTSIDE_PERMISSION_WINDOW = "CHAIN_SEND_OUTSIDE_PERMISSION_WINDOW"
CHAIN_TEMPORAL_ORDER = "CHAIN_TEMPORAL_ORDER"
CHAIN_RUN_ID_MISMATCH = "CHAIN_RUN_ID_MISMATCH"
CHAIN_BRAND_ID_MISMATCH = "CHAIN_BRAND_ID_MISMATCH"


@dataclass(frozen=True, order=True)
class Finding:
    """One validation failure. Any finding means the artifact or chain is invalid."""

    code: str
    artifact_id: str | None
    path: str
    message: str
    keyword: str | None = None

    def as_dict(self) -> dict[str, str | None]:
        return {
            "code": self.code,
            "artifact_id": self.artifact_id,
            "path": self.path,
            "keyword": self.keyword,
            "message": self.message,
        }


def all_codes() -> frozenset[str]:
    """Every stable finding code defined in this module."""
    return frozenset(
        value
        for name, value in globals().items()
        if isinstance(value, str) and name.isupper() and name == value
    )
